import type { MenuItem } from "./types";

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    name: "Cachopo de la Casa",
    category: "Platos Principales",
    price: 18.9,
    description: "Ternera tierna, queso fundido y un toque de salsa roja casera sobre pan crujiente.",
    allergens: ["Gluten", "Lácteos"],
    image: "https://via.placeholder.com/400x800/111111/ffffff?text=Alma+Ibérica",
    featured: true,
  },
  {
    id: 2,
    name: "Paella de Mariscos",
    category: "Platos Principales",
    price: 21.5,
    description: "Arroz meloso con bogavante, mejillones, calamares y azafrán de la casa.",
    allergens: ["Mariscos"],
    image: "https://via.placeholder.com/400x800/151515/ffffff?text=Paella",
  },
  {
    id: 3,
    name: "Entrecot con Patatas",
    category: "Platos Principales",
    price: 24.0,
    description: "Filete de vacuno con salsa de chimichurri y patatas asadas al horno.",
    allergens: [],
    image: "https://via.placeholder.com/400x800/1b1b1b/ffffff?text=Entrecot",
  },
  {
    id: 4,
    name: "Trío de Picoteo",
    category: "Tapeo Selecto",
    price: 12.5,
    description: "Aperitivo de la casa con aceitunas, patatas crujientes y mejillones en escabeche.",
    allergens: ["Pescado"],
    image: "https://via.placeholder.com/400x800/171717/ffffff?text=Picoteo",
  },
  {
    id: 5,
    name: "Bravas de la Casa",
    category: "Tapeo Selecto",
    price: 6.8,
    description: "Patatas doradas con salsa brava casera y alioli suave de ajo.",
    allergens: ["Huevos"],
    image: "https://via.placeholder.com/400x800/1e1e1e/ffffff?text=Bravas",
  },
  {
    id: 6,
    name: "Croquetas de Jamón",
    category: "Tapeo Selecto",
    price: 9.5,
    description: "Croquetas cremosa con jamón ibérico y toque de nuez moscada.",
    allergens: ["Gluten", "Lácteos", "Huevos"],
    image: "https://via.placeholder.com/400x800/141414/ffffff?text=Croquetas",
  },
  {
    id: 7,
    name: "Bocadillo de Calamares",
    category: "Bocadillos",
    price: 10.2,
    description: "Calamares tiernos con alioli, lechuga y una brioche tostada.",
    allergens: ["Gluten", "Mariscos"],
    image: "https://via.placeholder.com/400x800/1a1a1a/ffffff?text=Bocadillo",
  },
  {
    id: 8,
    name: "Bocadillo de Jamón Ibérico",
    category: "Bocadillos",
    price: 13.8,
    description: "Jamón de bellota cortado al momento, tomate y aceite de oliva virgen extra.",
    allergens: ["Gluten"],
    image: "https://via.placeholder.com/400x800/121212/ffffff?text=Jamón",
  },
  {
    id: 9,
    name: "Bocadillo de Tortilla",
    category: "Bocadillos",
    price: 7.4,
    description: "Tortilla de patata con cebolla caramelizada y pimientos asados.",
    allergens: ["Gluten", "Huevos"],
    image: "https://via.placeholder.com/400x800/181818/ffffff?text=Tortilla",
  },
  {
    id: 10,
    name: "Vermut de la Casa",
    category: "Bebidas",
    price: 5.5,
    description: "Vermut rojo artesanal con naranja y especias aromáticas.",
    allergens: [],
    image: "https://via.placeholder.com/400x800/101010/ffffff?text=Vermut",
  },
  {
    id: 11,
    name: "Tinto de Verano",
    category: "Bebidas",
    price: 4.8,
    description: "Refrescante mezcla de vino tinto, limón y soda con hielo.",
    allergens: [],
    image: "https://via.placeholder.com/400x800/0f0f0f/ffffff?text=Verano",
  },
  {
    id: 12,
    name: "Caña Fresca",
    category: "Bebidas",
    price: 2.6,
    description: "Cerveza bien tirada, fría y servida con el toque de Alma Ibérica.",
    allergens: [],
    image: "https://via.placeholder.com/400x800/111111/ffffff?text=Caña",
  },
];
